swiftmailer:
    transport:        smtp
    username:         Interweave Solutions
    password:         U7srKWKYNJ_L_kEyWH-f1g
    host:             smtp.mandrillapp.com
    port:             587
    encryption:       tls
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
