swiftmailer:
    transport:        smtp
    username:         platform.interweavesolutions
    password:         23t465209KJHLKJlgrjoiu543
    host:             mail.tesrack.com
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
