# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    AFG: AF
    ALA: AX
    ALB: AL
    DEU: DE
    AND: AD
    AGO: AO
    AIA: AI
    ATA: AQ
    ATG: AG
    ANT: AN
    SAU: SA
    DZA: DZ
    ARG: AR
    ARM: AM
    ABW: AW
    AUS: AU
    AUT: AT
    AZE: AZ
    BHS: BS
    BHR: BH
    BGD: BD
    BRB: BB
    BLR: BY
    BEL: BE
    BLZ: BZ
    BEN: BJ
    BMU: BM
    BTN: BT
    BOL: BO
    BIH: BA
    BWA: BW
    BVT: BV
    BRA: BR
    BRN: BN
    BGR: BG
    BFA: BF
    BDI: BI
    CPV: CV
    CYM: KY
    KHM: KH
    CMR: CM
    CAN: CA 
    CAF: CF
    TCD: TD
    CZE: CZ
    CHL: CL
    CHN: CN
    CYP: CY
    CCK: CC
    COL: CO
    COM: KM
    COG: CG
    COD: CD
    COK: CK
    PRK: KP
    KOR: KR
    CIV: CI
    CRI: CR
    HRV: HR
    CUB: CU
    DNK: DK
    DMA: DM
    DOM: DO
    ETH: ET
    ECU: EC
    GIN: GN
    GAB: GA
    HUN: HU
    IND: IN
    IDN: ID
    IRN: IR
    IRQ: IQ
    IRL: IE
    ISL: IS
    ISR: IL
    ITA: IT
    JAM: JM
    JPN: JP
    JEY: JE
    JOR: JO
    KAZ: KZ
    KEN: KE
    KGZ: KG
    KIR: KI
    KWT: KW
    LAO: LA
    LSO: LS
    LVA: LV
    LBN: LB
    LBR: LR
    LBY: LY
    LIE: LI
    LTU: LT
    LUX: LU
    MAC: MO
    MKD: MK
    MDG: MG
    MYS: MY
    MWI: MW
    MDV: MV
    MLI: ML
    MLT: MT
    FLK: FK
    IMN: IM
    MNP: MP
    MAR: MA
    MHL: MH
    MTQ: MQ
    MUS: MU
    MRT: MR
    MYT: YT
    MEX: MX
    FSM: FM
    MDA: MD
    MCO: MC
    MNG: MN
    MNE: ME
    MSR: MS
    MOZ: MZ
    MMR: MM
    NAM: NA
    NRU: NR
    CXR: CX
    NPL: NP
    NIC: NI
    NER: NE
    NGA: NG
    NIU: NU
    NFK: NF
    NOR: NO
    NCL: NC
    NZL: NZ
    OMN: OM
    NLD: NL
    PAK: PK
    PLW: PW
    PSE: PS
    PAN: PA
    PNG: PG
    PRY: PY
    PER: PE
    PCN: PN
    PYF: PF
    POL: PL
    PRT: PT
    PRI: PR
    QAT: QA
    GBR: GB
    REU: RE
    RWA: RW
    ROU: RO
    RUS: RU
    ESH: EH
    SLB: SB
    WSM: WS
    ASM: AS
    KNA: KN
    SMR: SM
    SPM: PM
    VCT: VC
    SHN: SH
    LCA: LC
    STP: ST
    SEN: SN
    SRB: RS
    SYC: SC
    SLE: SL
    SGP: SG
    SYR: SY
    SOM: SO
    LKA: LK
    SWZ: SZ
    ZAF: ZA
    SDN: SD
    SWE: SE
    CHE: CH
    SUR: SR
    SJM: SJ
    THA: TH
    TWN: TW
    TZA: TZ
    TJK: TJ
    IOT: IO
    ATF: TF
    TLS: TL
    TGO: TG
    TKL: TK
    TON: TO
    TTO: TT
    TUN: TN
    TCA: TC
    TKM: TM
    TUR: TR
    TUV: TV
    UKR: UA
    UGA: UG
    URY: UY
    UZB: UZ
    VUT: VU
    VAT: VA
    VEN: VE
    VNM: VN
    VGB: VG
    VIR: VI
    WLF: WF
    YEM: YE
    DJI: DJ
    ZMB: ZM
    ZWE: ZW
    DRC: CD
    SLV: SV
    GTM: GT
    GUY: GY
    GHA: GH
    HTI: HT
    HND: HN
    USA: US


    AF: Afghanistan
    AX: Åland Islands
    AL: Albania
    DZ: Algeria
    AS: American Samoa
    AD: Andorra
    AO: Angola
    AI: Anguilla
    AQ: Antarctica
    AG: Antigua and Barbuda
    AR: Argentina
    AM: Armenia
    AW: Aruba
    AU: Australia
    AT: Austria
    AZ: Azerbaijan
    BS: Bahamas
    BH: Bahrain
    BD: Bangladesh
    BB: Barbados
    BY: Belarus
    BE: Belgium
    BZ: Belize
    BJ: Benin
    BM: Bermuda
    BT: Bhutan
    BO: Bolivia
    BQ: Bonaire
    BA: Bosnia and Herzegovina
    BW: Botswana
    BV: Bouvet Island
    BR: Brazil
    IO: British Indian Ocean Territory
    BN: Brunei Darussalam
    BG: Bulgaria
    BF: Burkina Faso
    BI: Burundi
    KH: Cambodia
    CM: Cameroon
    CA: Canada
    CV: Cape Verde
    KY: Cayman Islands
    CF: Central African Republic
    TD: Chad
    CL: Chile
    CN: China
    CX: Christmas Island
    CC: Cocos (Keeling) Islands
    CO: Colombia
    KM: Comoros
    CG: Congo
    CD: Congo Democratic Republic
    CK: Cook Islands
    CR: Costa Rica
    CI: Côte d'Ivoire
    HR: Croatia
    CU: Cuba
    CW: Curaçao
    CY: Cyprus
    CZ: Czech Republic
    DK: Denmark
    DJ: Djibouti
    DM: Dominica
    DO: Dominican Republic
    EC: Ecuador
    EG: Egypt
    SV: El Salvador
    GQ: Equatorial Guinea
    ER: Eritrea
    EE: Estonia
    ET: Ethiopia
    FK: Falkland Islands (Malvinas)
    FO: Faroe Islands
    FJ: Fiji
    FI: Finland
    FR: France
    GF: French Guiana
    PF: French Polynesia
    TF: French Southern Territories
    GA: Gabon
    GM: Gambia
    GE: Georgia
    DE: Germany
    GH: Ghana
    GI: Gibraltar
    GR: Greece
    GL: Greenland
    GD: Grenada
    GP: Guadeloupe
    GU: Guam
    GT: Guatemala
    GG: Guernsey
    GN: Guinea
    GW: Guinea-Bissau
    GY: Guyana
    HT: Haiti
    HM: Heard Island and McDonald Islands
    VA: Holy See (Vatican City State)
    HN: Honduras
    HK: Hong Kong
    HU: Hungary
    IS: Iceland
    IN: India
    ID: Indonesia
    IR: Iran, Islamic Republic of
    IQ: Iraq
    IE: Ireland
    IM: Isle of Man
    IL: Israel
    IT: Italy
    JM: Jamaica
    JP: Japan
    JE: Jersey
    JO: Jordan
    KZ: Kazakhstan
    KE: Kenya
    KI: Kiribati
    KP: Korea, Democratic People's Republic of
    KR: Korea, Republic of
    KW: Kuwait
    KG: Kyrgyzstan
    LA: Lao People's Democratic Republic
    LV: Latvia
    LB: Lebanon
    LS: Lesotho
    LR: Liberia
    LY: Libya
    LI: Liechtenstein
    LT: Lithuania
    LU: Luxembourg
    MO: Macao
    MK: Macedonia, the former Yugoslav Republic of
    MG: Madagascar
    MW: Malawi
    MY: Malaysia
    MV: Maldives
    ML: Mali
    MT: Malta
    MH: Marshall Islands
    MQ: Martinique
    MR: Mauritania
    MU: Mauritius
    YT: Mayotte
    MX: Mexico
    FM: Micronesia, Federated States of
    MD: Moldova, Republic of
    MC: Monaco
    MN: Mongolia
    ME: Montenegro
    MS: Montserrat
    MA: Morocco
    MZ: Mozambique
    MM: Myanmar
    NA: Namibia
    NR: Nauru
    NP: Nepal
    NL: Netherlands
    NC: New Caledonia
    NZ: New Zealand
    NI: Nicaragua
    NE: Niger
    NG: Nigeria
    NU: Niue
    NF: Norfolk Island
    MP: Northern Mariana Islands
    NO: Norway
    OM: Oman
    PK: Pakistan
    PW: Palau
    PS: Palestinian Territory, Occupied
    PA: Panama
    PG: Papua New Guinea
    PY: Paraguay
    PE: Peru
    PH: Philippines
    PN: Pitcairn
    PL: Poland
    PT: Portugal
    PR: Puerto Rico
    QA: Qatar
    RE: Réunion
    RO: Romania
    RU: Russian Federation
    RW: Rwanda
    BL: Saint Barthélemy
    SH: Saint Helena, Ascension and Tristan da Cunha
    KN: Saint Kitts and Nevis
    LC: Saint Lucia
    MF: Saint Martin (French part)
    PM: Saint Pierre and Miquelon
    VC: Saint Vincent and the Grenadines
    WS: Samoa
    SM: San Marino
    ST: Sao Tome and Principe
    SA: Saudi Arabia
    SN: Senegal
    RS: Serbia
    SC: Seychelles
    SL: Sierra Leone
    SG: Singapore
    SX: Sint Maarten (Dutch part)
    SK: Slovakia
    SI: Slovenia
    SB: Solomon Islands
    SO: Somalia
    ZA: South Africa
    GS: South Georgia and the South Sandwich Islands
    SS: South Sudan
    ES: Spain
    LK: Sri Lanka
    SD: Sudan
    SR: Suriname
    SJ: Svalbard and Jan Mayen
    SZ: Swaziland
    SE: Sweden
    CH: Switzerland
    SY: Syrian Arab Republic
    TW: Taiwan, Province of China
    TJ: Tajikistan
    TZ: Tanzania, United Republic of
    TH: Thailand
    TL: Timor-Leste
    TG: Togo
    TK: Tokelau
    TO: Tonga
    TT: Trinidad and Tobago
    TN: Tunisia
    TR: Turkey
    TM: Turkmenistan
    TC: Turks and Caicos Islands
    TV: Tuvalu
    UG: Uganda
    UA: Ukraine
    AE: United Arab Emirates
    GB: United Kingdom
    US: United States
    UM: United States Minor Outlying Islands
    UY: Uruguay
    UZ: Uzbekistan
    VU: Vanuatu
    VE: Venezuela, Bolivarian Republic of
    VN: Viet Nam
    VG: Virgin Islands, British
    VI: Virgin Islands, U.S.
    WF: Wallis and Futuna
    EH: Western Sahara
    YE: Yemen
    ZM: Zambia
    ZW: Zimbabwe

    # Email Messages
    subject.change_password_en: Need to change your password?     
    subject.created_group_en:   SA PLATFORM - New Group Created
    message.created_group_en:   The following ambassador has created a group
    
    subject.change_password_es: Need to change your password?     
    subject.created_group_es:   SA PLATFORM - New Group Created
    message.created_group_es:   The following ambassador has created a group

    subject.change_password_fr: Need to change your password?     
    subject.created_group_fr:   SA PLATFORM - New Group Created
    message.created_group_fr:   The following ambassador has created a group

    subject.change_password_pr: Need to change your password?     
    subject.created_group_pr:   SA PLATFORM - New Group Created
    message.created_group_pr:   The following ambassador has created a group




services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    white_october.tcpdf.public:
        alias: white_october.tcpdf
        public: true

    # mi_api.event.jwt_created_listener:
    #    class: App\Event\Listener\JWTCreatedListener
    #    tags:
    #    - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
